controller:
  image: jenkins/jenkins:lts-jdk17
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - configuration-as-code
    - git
    - credentials-binding
  resources:
    requests:
      cpu: "500m"
      memory: "1.5Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  # Persist Jenkins data using local-path
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 20Gi

  # Stick controller pod to controller node
  nodeSelector:
    jenkins: controller
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: jenkins
                operator: In
                values: ["controller"]

  # Expose without domain → NodePort
  serviceType: NodePort
  nodePort: 32080

  # Bootstrap admin user
  adminUser: admin
  adminPassword: ""

  # Auto-config Kubernetes cloud for agents
  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      kubernetes-cloud.yaml: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                namespace: "jenkins"
                serverUrl: "https://kubernetes.default.svc"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                containerCapStr: "50"
                templates:
                  - name: "default"
                    label: "k8s"
                    yaml: |
                      apiVersion: v1
                      kind: Pod
                      metadata:
                        labels:
                          jenkins: agent
                      spec:
                        nodeSelector:
                          jenkins: agent
                        restartPolicy: Never
                        containers:
                          - name: jnlp
                            image: jenkins/inbound-agent:latest-jdk17
                            resources:
                              requests:
                                cpu: "200m"
                                memory: "512Mi"
                              limits:
                                cpu: "2"
                                memory: "2Gi"

agent:
  enabled: true   # service for inbound agents (tcp 50000)

rbac:
  create: true
