controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts-jdk17
    pullPolicy: IfNotPresent

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - configuration-as-code
    - git
    - credentials-binding

  resources:
    requests:
      cpu: "500m"
      memory: "1.5Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 20Gi

  nodeSelector:
    jenkins: controller
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: jenkins
                operator: In
                values: ["controller"]

  serviceType: NodePort
  nodePort: 32080

  adminUser: admin
  adminPassword: ""

  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      kubernetes-cloud.yaml: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                namespace: "jenkins"
                serverUrl: "https://kubernetes.default.svc"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                containerCapStr: "50"
                templates:
                  - name: "default"
                    label: "k8s"
                    yaml: |
                      apiVersion: v1
                      kind: Pod
                      spec:
                        nodeSelector:
                          jenkins: agent
                        restartPolicy: Never
                        containers:
                          - name: jnlp
                            image: jenkins/inbound-agent:latest-jdk17
                            resources:
                              requests:
                                cpu: "200m"
                                memory: "512Mi"
                              limits:
                                cpu: "2"
                                memory: "2Gi"

agent:
  enabled: true

rbac:
  create: true
